[env]
term="tmux-256color"

[general]
import = [
    "~/.config/alacritty/themes/rose-pine.toml"
]

[window]
opacity = 0.8
blur = true

[font]
size = 12.0

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

